import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { BRAND_CONFIG } from '../config/brand';
import {
  ArrowDownCircle,
  Copy,
  Check,
  AlertTriangle,
  QrCode,
  ShieldCheck,
  RefreshCw,
  ExternalLink,
  Clock,
  ArrowRight,
} from 'lucide-react';

export const DepositPage: React.FC = () => {
  const { wallet, depositFunds, addToast, navigateTo } = useApp();

  const [network, setNetwork] = useState<'BEP20' | 'TRC20'>('BEP20');
  const [amount, setAmount] = useState<number>(10);
  const [step, setStep] = useState<'form' | 'payment' | 'complete'>('form');
  const [isProcessing, setIsProcessing] = useState(false);
  const [txStatus, setTxStatus] = useState<'Pending' | 'Confirmed' | 'Failed'>('Pending');
  const [copied, setCopied] = useState(false);

  // Simulated provider checkout invoice identifier
  const [invoiceId, setInvoiceId] = useState('');

  const minDeposit = BRAND_CONFIG.deposit.minAmount;

  const handleStartDeposit = (e: React.FormEvent) => {
    e.preventDefault();
    if (amount < minDeposit) {
      addToast(`Minimum deposit is ${minDeposit} USDT`, 'error');
      return;
    }

    const mockInvoice = `HLK-${network}-${Math.floor(100000 + Math.random() * 900000)}`;
    setInvoiceId(mockInvoice);
    setStep('payment');
    setTxStatus('Pending');
  };

  const handleSimulatePaymentConfirmation = async () => {
    setIsProcessing(true);
    setTxStatus('Pending');

    // Simulate backend / HELEKET payment confirmation
    setTimeout(async () => {
      await depositFunds(amount, network);
      setTxStatus('Confirmed');
      setIsProcessing(false);
      setStep('complete');
    }, 1500);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    addToast('Payment reference copied to clipboard', 'info');
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8 pb-24">
      {/* Header */}
      <div>
        <span className="text-xs uppercase tracking-wider text-purple-400 font-semibold">
          Wallet Funding
        </span>
        <h1 className="text-2xl sm:text-3xl font-extrabold text-white mt-1">
          Deposit USDT
        </h1>
        <p className="text-xs sm:text-sm text-slate-300 mt-1">
          Deposit USDT via supported blockchain networks. Processed through the {BRAND_CONFIG.deposit.provider} payment gateway framework.
        </p>
      </div>

      {/* Provider Integration Notice */}
      <div className="p-4 rounded-xl bg-purple-950/20 border border-purple-500/20 text-xs text-slate-300 space-y-1">
        <div className="flex items-center gap-2 text-purple-300 font-semibold">
          <ShieldCheck className="w-4 h-4 text-purple-400" />
          <span>Payment Gateway: {BRAND_CONFIG.deposit.provider} Integration Framework</span>
        </div>
        <p className="text-slate-400 leading-relaxed text-[11px]">
          In production, designated recipient blockchain addresses are dynamically generated by the secure {BRAND_CONFIG.deposit.provider} API server. Private keys are never exposed in client code.
        </p>
      </div>

      {step === 'form' && (
        <form onSubmit={handleStartDeposit} className="rounded-2xl bg-[#111526] border border-white/[0.08] p-6 sm:p-8 space-y-6">
          {/* Step 1: Select Network */}
          <div className="space-y-3">
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-300">
              Step 1: Choose USDT Transfer Network
            </label>
            <div className="grid grid-cols-2 gap-4">
              <button
                type="button"
                onClick={() => setNetwork('BEP20')}
                className={`p-4 rounded-xl text-left border transition cursor-pointer ${
                  network === 'BEP20'
                    ? 'bg-purple-950/40 border-purple-500 text-white shadow-md shadow-purple-600/20'
                    : 'bg-[#15192C] border-white/[0.08] text-slate-400 hover:text-white'
                }`}
              >
                <div className="flex items-center justify-between mb-1">
                  <span className="font-bold text-sm text-white">USDT (BEP20)</span>
                  <span className="text-[10px] px-2 py-0.5 rounded bg-emerald-950 text-emerald-300 border border-emerald-500/30">
                    BSC Fast
                  </span>
                </div>
                <p className="text-[11px] text-slate-400">BNB Smart Chain Network</p>
              </button>

              <button
                type="button"
                onClick={() => setNetwork('TRC20')}
                className={`p-4 rounded-xl text-left border transition cursor-pointer ${
                  network === 'TRC20'
                    ? 'bg-purple-950/40 border-purple-500 text-white shadow-md shadow-purple-600/20'
                    : 'bg-[#15192C] border-white/[0.08] text-slate-400 hover:text-white'
                }`}
              >
                <div className="flex items-center justify-between mb-1">
                  <span className="font-bold text-sm text-white">USDT (TRC20)</span>
                  <span className="text-[10px] px-2 py-0.5 rounded bg-sky-950 text-sky-300 border border-sky-500/30">
                    Tron Low Fee
                  </span>
                </div>
                <p className="text-[11px] text-slate-400">Tron TRC-20 Network</p>
              </button>
            </div>
          </div>

          {/* Step 2: Amount */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <label className="text-xs font-semibold uppercase tracking-wider text-slate-300">
                Step 2: Enter Deposit Amount (USDT)
              </label>
              <span className="text-xs text-slate-400">
                Minimum Deposit: <strong className="text-purple-300 font-mono">{minDeposit} USDT</strong>
              </span>
            </div>

            <div className="relative">
              <input
                type="number"
                min={minDeposit}
                step="any"
                required
                value={amount}
                onChange={(e) => setAmount(Number(e.target.value))}
                className="w-full bg-[#15192C] border border-white/[0.1] focus:border-purple-500 rounded-xl px-4 py-3 text-lg font-mono text-white placeholder-slate-500 focus:outline-none transition shadow-inner"
              />
              <span className="absolute right-4 top-3.5 text-sm font-bold text-purple-400 font-mono">
                USDT
              </span>
            </div>

            {/* Quick preset buttons */}
            <div className="flex gap-2">
              {[5, 10, 20, 50, 100].map((preset) => (
                <button
                  key={preset}
                  type="button"
                  onClick={() => setAmount(preset)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-mono transition cursor-pointer ${
                    amount === preset
                      ? 'bg-purple-600 text-white'
                      : 'bg-[#171C30] text-slate-400 hover:text-white border border-white/[0.04]'
                  }`}
                >
                  +{preset} USDT
                </button>
              ))}
            </div>
          </div>

          {/* Applicable Deposit Information */}
          <div className="p-4 rounded-xl bg-[#0C0F1A] border border-white/[0.06] space-y-2 text-xs text-slate-400">
            <div className="flex justify-between">
              <span>Transfer Currency:</span>
              <span className="font-semibold text-white">USDT (Tether USD)</span>
            </div>
            <div className="flex justify-between">
              <span>Selected Network:</span>
              <span className="font-semibold text-purple-300 font-mono">{network}</span>
            </div>
            <div className="flex justify-between">
              <span>Minimum Threshold:</span>
              <span className="font-semibold text-white font-mono">{minDeposit} USDT</span>
            </div>
            <div className="flex justify-between">
              <span>Provider Routing:</span>
              <span className="text-slate-300">{BRAND_CONFIG.deposit.provider} Gateway Session</span>
            </div>
          </div>

          <button
            type="submit"
            className="w-full py-3 rounded-xl bg-purple-600 hover:bg-purple-500 text-white font-semibold text-sm shadow-lg shadow-purple-600/30 transition flex items-center justify-center gap-2 cursor-pointer"
          >
            <span>Generate Deposit Invoice</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </form>
      )}

      {step === 'payment' && (
        <div className="rounded-2xl bg-[#111526] border border-purple-500/30 p-6 sm:p-8 space-y-6">
          <div className="flex items-center justify-between border-b border-white/[0.08] pb-4">
            <div>
              <span className="text-xs text-purple-400 font-mono font-semibold">
                {invoiceId}
              </span>
              <h2 className="text-xl font-bold text-white mt-0.5">
                {BRAND_CONFIG.deposit.provider} Payment Instructions
              </h2>
            </div>
            <div className="px-3 py-1 rounded-full text-xs font-semibold bg-amber-950/60 text-amber-300 border border-amber-500/30 flex items-center gap-1.5">
              <Clock className="w-3.5 h-3.5 animate-spin" style={{ animationDuration: '4s' }} />
              Status: {txStatus}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Visual QR Placeholder */}
            <div className="p-4 rounded-xl bg-[#0B0E1B] border border-white/[0.08] flex flex-col items-center justify-center text-center">
              <div className="w-36 h-36 bg-white p-2 rounded-lg flex items-center justify-center shadow-lg">
                <QrCode className="w-32 h-32 text-slate-900" />
              </div>
              <span className="text-[11px] text-slate-400 mt-3 font-mono">
                Scan via {network} Wallet
              </span>
            </div>

            {/* Instruction details */}
            <div className="md:col-span-2 space-y-4 text-xs">
              <div>
                <span className="text-slate-400 block mb-1">Exact Amount to Send:</span>
                <div className="text-2xl font-black font-mono text-purple-300">
                  {amount} USDT
                </div>
              </div>

              <div>
                <span className="text-slate-400 block mb-1">Network Requirement:</span>
                <span className="text-sm font-bold text-white font-mono bg-[#171C30] px-2.5 py-1 rounded border border-white/[0.08]">
                  USDT-{network}
                </span>
                <p className="text-[11px] text-red-400 mt-1">
                  * Sending over any network other than {network} will result in irreversible deposit loss.
                </p>
              </div>

              <div>
                <span className="text-slate-400 block mb-1">
                  Payment Reference / Invoice Gateway ID:
                </span>
                <div className="flex items-center gap-2">
                  <input
                    type="text"
                    readOnly
                    value={invoiceId}
                    className="w-full bg-[#15192C] border border-white/[0.1] rounded-lg px-3 py-2 text-xs font-mono text-slate-300"
                  />
                  <button
                    type="button"
                    onClick={() => copyToClipboard(invoiceId)}
                    className="p-2 rounded-lg bg-[#1D223B] hover:bg-[#282F52] text-slate-300 transition"
                  >
                    {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                  </button>
                </div>
              </div>

              <div className="p-3 rounded-lg bg-[#0F1220] border border-white/[0.06] text-[11px] text-slate-400">
                Addresses are generated uniquely per session by the payment provider. Do not reuse old invoices.
              </div>
            </div>
          </div>

          {/* Action buttons */}
          <div className="pt-4 border-t border-white/[0.08] flex flex-col sm:flex-row items-center justify-between gap-4">
            <button
              type="button"
              onClick={() => setStep('form')}
              className="text-xs text-slate-400 hover:text-white transition"
            >
              ← Cancel or modify amount
            </button>

            <button
              type="button"
              disabled={isProcessing}
              onClick={handleSimulatePaymentConfirmation}
              className="w-full sm:w-auto px-6 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-500 text-white font-semibold text-xs shadow-lg shadow-purple-600/30 transition flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
            >
              {isProcessing ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  <span>Verifying with {BRAND_CONFIG.deposit.provider}...</span>
                </>
              ) : (
                <>
                  <span>Simulate Payment Receipt</span>
                  <ArrowRight className="w-4 h-4" />
                </>
              )}
            </button>
          </div>
        </div>
      )}

      {step === 'complete' && (
        <div className="rounded-2xl bg-[#111526] border border-emerald-500/30 p-8 text-center max-w-lg mx-auto space-y-4">
          <div className="w-12 h-12 rounded-full bg-emerald-950 text-emerald-400 border border-emerald-500/30 flex items-center justify-center mx-auto">
            <Check className="w-6 h-6" />
          </div>

          <h2 className="text-xl font-bold text-white">Deposit Confirmed!</h2>
          <p className="text-xs text-slate-300 leading-relaxed">
            Your transfer of <strong className="text-emerald-400 font-mono">+{amount} USDT</strong> via {network} has been confirmed by {BRAND_CONFIG.deposit.provider} and credited to your available balance.
          </p>

          <div className="p-3 rounded-xl bg-[#0B0E1B] text-xs font-mono text-slate-300 flex justify-between">
            <span>New Wallet Balance:</span>
            <span className="font-bold text-white">{wallet.availableBalance} USDT</span>
          </div>

          <div className="pt-2 flex gap-3 justify-center">
            <button
              onClick={() => navigateTo('dashboard')}
              className="px-5 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-500 text-white text-xs font-semibold shadow-md shadow-purple-600/30 transition cursor-pointer"
            >
              Go to Dashboard
            </button>
            <button
              onClick={() => {
                setStep('form');
                setAmount(10);
              }}
              className="px-5 py-2.5 rounded-xl bg-[#171C30] hover:bg-[#1E2540] text-slate-200 text-xs font-semibold transition cursor-pointer"
            >
              Deposit Again
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
